# Generated by Django 3.0.7 on 2020-06-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['level', 'string']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['depth']},
        ),
        migrations.AddConstraint(
            model_name='code',
            constraint=models.UniqueConstraint(fields=('level', 'string'), name='level, string'),
        ),
    ]
