# Generated by Django 3.0.7 on 2020-06-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20200606_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='title',
            field=models.CharField(default='-_-_-_-_-_-_-', max_length=128),
            preserve_default=False,
        ),
    ]
